/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-07-GitHub-Hexo初次建站简单流程与问题': RouteRecordInfo<'/posts/2024-12-07-GitHub-Hexo初次建站简单流程与问题', '/posts/2024-12-07-GitHub-Hexo初次建站简单流程与问题', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-07-HTML-CSS笔记': RouteRecordInfo<'/posts/2024-12-07-HTML-CSS笔记', '/posts/2024-12-07-HTML-CSS笔记', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-08-GithHub-Hexo-VUE单页面主题的问题': RouteRecordInfo<'/posts/2024-12-08-GithHub-Hexo-VUE单页面主题的问题', '/posts/2024-12-08-GithHub-Hexo-VUE单页面主题的问题', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-10-《真-安全键盘》-灵感来自于河北农信的密码输入键盘': RouteRecordInfo<'/posts/2024-12-10-《真-安全键盘》-灵感来自于河北农信的密码输入键盘', '/posts/2024-12-10-《真-安全键盘》-灵感来自于河北农信的密码输入键盘', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-21-【wallpaper教程】web壁纸制作': RouteRecordInfo<'/posts/2024-12-21-【wallpaper教程】web壁纸制作', '/posts/2024-12-21-【wallpaper教程】web壁纸制作', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-31-MC-WEB-UI设计与站点设计稿': RouteRecordInfo<'/posts/2024-12-31-MC-WEB-UI设计与站点设计稿', '/posts/2024-12-31-MC-WEB-UI设计与站点设计稿', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-31-MC-WEB系统前端UI设计': RouteRecordInfo<'/posts/2024-12-31-MC-WEB系统前端UI设计', '/posts/2024-12-31-MC-WEB系统前端UI设计', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-31-新Flag立项-MC-WEB集成系统开发': RouteRecordInfo<'/posts/2024-12-31-新Flag立项-MC-WEB集成系统开发', '/posts/2024-12-31-新Flag立项-MC-WEB集成系统开发', Record<never, never>, Record<never, never>>,
    '/posts/2025-01-01-PHP-Laravel框架win环境部署与问题解决': RouteRecordInfo<'/posts/2025-01-01-PHP-Laravel框架win环境部署与问题解决', '/posts/2025-01-01-PHP-Laravel框架win环境部署与问题解决', Record<never, never>, Record<never, never>>,
    '/posts/2025-01-19-VUE-Game笔记': RouteRecordInfo<'/posts/2025-01-19-VUE-Game笔记', '/posts/2025-01-19-VUE-Game笔记', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/2024-12-07-GitHub-Hexo初次建站简单流程与问题.md': {
      routes: '/posts/2024-12-07-GitHub-Hexo初次建站简单流程与问题'
      views: never
    }
    'pages/posts/2024-12-07-HTML-CSS笔记.md': {
      routes: '/posts/2024-12-07-HTML-CSS笔记'
      views: never
    }
    'pages/posts/2024-12-08-GithHub-Hexo-VUE单页面主题的问题.md': {
      routes: '/posts/2024-12-08-GithHub-Hexo-VUE单页面主题的问题'
      views: never
    }
    'pages/posts/2024-12-10-《真-安全键盘》-灵感来自于河北农信的密码输入键盘.md': {
      routes: '/posts/2024-12-10-《真-安全键盘》-灵感来自于河北农信的密码输入键盘'
      views: never
    }
    'pages/posts/2024-12-21-【wallpaper教程】web壁纸制作.md': {
      routes: '/posts/2024-12-21-【wallpaper教程】web壁纸制作'
      views: never
    }
    'pages/posts/2024-12-31-MC-WEB-UI设计与站点设计稿.md': {
      routes: '/posts/2024-12-31-MC-WEB-UI设计与站点设计稿'
      views: never
    }
    'pages/posts/2024-12-31-MC-WEB系统前端UI设计.md': {
      routes: '/posts/2024-12-31-MC-WEB系统前端UI设计'
      views: never
    }
    'pages/posts/2024-12-31-新Flag立项-MC-WEB集成系统开发.md': {
      routes: '/posts/2024-12-31-新Flag立项-MC-WEB集成系统开发'
      views: never
    }
    'pages/posts/2025-01-01-PHP-Laravel框架win环境部署与问题解决.md': {
      routes: '/posts/2025-01-01-PHP-Laravel框架win环境部署与问题解决'
      views: never
    }
    'pages/posts/2025-01-19-VUE-Game笔记.md': {
      routes: '/posts/2025-01-19-VUE-Game笔记'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
