/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-07-github-hexo-first-site-setup': RouteRecordInfo<'/posts/2024-12-07-github-hexo-first-site-setup', '/posts/2024-12-07-github-hexo-first-site-setup', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-07-html-css-notes': RouteRecordInfo<'/posts/2024-12-07-html-css-notes', '/posts/2024-12-07-html-css-notes', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-08-github-hexo-vue-spa-theme-issues': RouteRecordInfo<'/posts/2024-12-08-github-hexo-vue-spa-theme-issues', '/posts/2024-12-08-github-hexo-vue-spa-theme-issues', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-10-secure-keyboard-inspiration': RouteRecordInfo<'/posts/2024-12-10-secure-keyboard-inspiration', '/posts/2024-12-10-secure-keyboard-inspiration', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-21-wallpaper-engine-web-tutorial': RouteRecordInfo<'/posts/2024-12-21-wallpaper-engine-web-tutorial', '/posts/2024-12-21-wallpaper-engine-web-tutorial', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-31-mc-web-frontend-ui-design': RouteRecordInfo<'/posts/2024-12-31-mc-web-frontend-ui-design', '/posts/2024-12-31-mc-web-frontend-ui-design', Record<never, never>, Record<never, never>>,
    '/posts/2024-12-31-mc-web-integration-system-project': RouteRecordInfo<'/posts/2024-12-31-mc-web-integration-system-project', '/posts/2024-12-31-mc-web-integration-system-project', Record<never, never>, Record<never, never>>,
    '/posts/2025-01-01-php-laravel-windows-deployment': RouteRecordInfo<'/posts/2025-01-01-php-laravel-windows-deployment', '/posts/2025-01-01-php-laravel-windows-deployment', Record<never, never>, Record<never, never>>,
    '/posts/2025-01-19-vue-game-notes': RouteRecordInfo<'/posts/2025-01-19-vue-game-notes', '/posts/2025-01-19-vue-game-notes', Record<never, never>, Record<never, never>>,
    '/posts/2025-10-23-newblog': RouteRecordInfo<'/posts/2025-10-23-newblog', '/posts/2025-10-23-newblog', Record<never, never>, Record<never, never>>,
    '/posts/2025-10-26-how-to-use-mstsc-in-your-winpc': RouteRecordInfo<'/posts/2025-10-26-how-to-use-mstsc-in-your-winpc', '/posts/2025-10-26-how-to-use-mstsc-in-your-winpc', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/2024-12-07-github-hexo-first-site-setup.md': {
      routes: '/posts/2024-12-07-github-hexo-first-site-setup'
      views: never
    }
    'pages/posts/2024-12-07-html-css-notes.md': {
      routes: '/posts/2024-12-07-html-css-notes'
      views: never
    }
    'pages/posts/2024-12-08-github-hexo-vue-spa-theme-issues.md': {
      routes: '/posts/2024-12-08-github-hexo-vue-spa-theme-issues'
      views: never
    }
    'pages/posts/2024-12-10-secure-keyboard-inspiration.md': {
      routes: '/posts/2024-12-10-secure-keyboard-inspiration'
      views: never
    }
    'pages/posts/2024-12-21-wallpaper-engine-web-tutorial.md': {
      routes: '/posts/2024-12-21-wallpaper-engine-web-tutorial'
      views: never
    }
    'pages/posts/2024-12-31-mc-web-frontend-ui-design.md': {
      routes: '/posts/2024-12-31-mc-web-frontend-ui-design'
      views: never
    }
    'pages/posts/2024-12-31-mc-web-integration-system-project.md': {
      routes: '/posts/2024-12-31-mc-web-integration-system-project'
      views: never
    }
    'pages/posts/2025-01-01-php-laravel-windows-deployment.md': {
      routes: '/posts/2025-01-01-php-laravel-windows-deployment'
      views: never
    }
    'pages/posts/2025-01-19-vue-game-notes.md': {
      routes: '/posts/2025-01-19-vue-game-notes'
      views: never
    }
    'pages/posts/2025-10-23-newblog.md': {
      routes: '/posts/2025-10-23-newblog'
      views: never
    }
    'pages/posts/2025-10-26-how-to-use-mstsc-in-your-winpc.md': {
      routes: '/posts/2025-10-26-how-to-use-mstsc-in-your-winpc'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
